# Generated by Django 5.2.7 on 2025-10-28 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditUnion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The full legal name of the credit union.', max_length=255, unique=True)),
                ('address', models.TextField(blank=True, help_text='The physical address.')),
                ('contact_email', models.EmailField(blank=True, help_text='Main contact email for the union.', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(help_text='The associated default Django user.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('credit_union', models.ForeignKey(blank=True, help_text='The Credit Union the user belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='credit_unions.creditunion')),
            ],
        ),
    ]
