# Generated by Django 4.1.7 on 2025-06-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('annual_interest_rate_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('loan_term_years', models.IntegerField()),
                ('borrower_gross_monthly_income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('existing_monthly_debt_payments', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit_score', models.CharField(blank=True, max_length=50, null=True)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('reasons', models.JSONField(default=list)),
                ('monthly_payment_new_loan', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_monthly_debt', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('dti_ratio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('loan_amount_to_annual_income_ratio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]
