# Generated by Django 5.2.3 on 2025-08-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
