# Generated by Django 5.2.3 on 2025-06-30 10:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MortgageLoanApplication',
            fields=[
                ('loanapplication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calculator.loanapplication')),
                ('has_legal_mortgage_agreement', models.BooleanField(default=False)),
                ('has_land_title_in_borrower_name', models.BooleanField(default=False)),
                ('has_power_of_attorney', models.BooleanField(default=False)),
                ('has_full_kyc', models.BooleanField(default=False)),
                ('loan_purpose_valid', models.BooleanField(default=False)),
                ('has_supporting_documents', models.BooleanField(default=False)),
                ('no_existing_npl', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Mortgage Loan Application',
                'verbose_name_plural': 'Mortgage Loan Applications',
            },
            bases=('calculator.loanapplication',),
        ),
        migrations.RenameField(
            model_name='loanapplication',
            old_name='application_date',
            new_name='submission_date',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='credit_score',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='dti_ratio',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='loan_amount_to_annual_income_ratio',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='monthly_payment_new_loan',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='total_monthly_debt',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='applicant_email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='applicant_name',
            field=models.CharField(default='Default Applicant', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='appraisal_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='loan_type',
            field=models.CharField(choices=[('mortgage', 'Mortgage Loan'), ('salary_backed', 'Salary-Backed Loan'), ('within_savings', 'Loan Within Savings'), ('above_savings', 'Loan Above Savings'), ('standing_order', 'Standing Order Loan')], default='mortgage', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='reasons',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
