# Generated by Django 5.2.7 on 2025-10-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_loanapplication_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agriculturalloanapplication',
            name='loan_purpose_category',
            field=models.CharField(blank=True, help_text='Select the primary purpose of this agricultural loan.', max_length=50, null=True),
        ),
    ]
