# Generated by Django 5.2.3 on 2025-06-30 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_mortgageloanapplication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanAboveSavingsApplication',
            fields=[
                ('loanapplication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calculator.loanapplication')),
                ('daily_savings_active_ge_6_months', models.BooleanField(default=False)),
                ('has_signed_deduction_agreement', models.BooleanField(default=False)),
                ('has_valid_surety_bond', models.BooleanField(default=False)),
                ('positive_loan_repayment_history', models.BooleanField(default=False)),
                ('savings_balance_ge_1_5_loan', models.BooleanField(default=False)),
                ('has_full_kyc', models.BooleanField(default=False)),
                ('loan_purpose_clearly_defined', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Loan Above Savings Application',
                'verbose_name_plural': 'Loan Above Savings Applications',
            },
            bases=('calculator.loanapplication',),
        ),
        migrations.CreateModel(
            name='LoanWithinSavingsApplication',
            fields=[
                ('loanapplication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calculator.loanapplication')),
                ('savings_covers_loan_plus_interest', models.BooleanField(default=False)),
                ('loan_amount_blocked_in_savings', models.BooleanField(default=False)),
                ('has_full_kyc', models.BooleanField(default=False)),
                ('loan_purpose_clearly_defined', models.BooleanField(default=False)),
                ('no_active_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Loan Within Savings Application',
                'verbose_name_plural': 'Loan Within Savings Applications',
            },
            bases=('calculator.loanapplication',),
        ),
        migrations.CreateModel(
            name='SalaryBackedLoanApplication',
            fields=[
                ('loanapplication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calculator.loanapplication')),
                ('salary_passing_union_ge_3_months', models.BooleanField(default=False)),
                ('has_copy_of_effective_service', models.BooleanField(default=False)),
                ('has_irrevocable_salary_transfer_doc', models.BooleanField(default=False)),
                ('savings_ge_1_10_loan', models.BooleanField(default=False)),
                ('has_full_kyc', models.BooleanField(default=False)),
                ('loan_purpose_clearly_defined', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Salary-Backed Loan Application',
                'verbose_name_plural': 'Salary-Backed Loan Applications',
            },
            bases=('calculator.loanapplication',),
        ),
        migrations.CreateModel(
            name='StandingOrderLoanApplication',
            fields=[
                ('loanapplication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calculator.loanapplication')),
                ('standing_order_active_ge_3_months', models.BooleanField(default=False)),
                ('loan_duration_le_1_year', models.BooleanField(default=False)),
                ('savings_balance_ge_1_5_loan', models.BooleanField(default=False)),
                ('has_full_kyc', models.BooleanField(default=False)),
                ('loan_purpose_clearly_defined', models.BooleanField(default=False)),
                ('no_existing_default_or_delinquency', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Standing Order Loan Application',
                'verbose_name_plural': 'Standing Order Loan Applications',
            },
            bases=('calculator.loanapplication',),
        ),
    ]
