# Generated by Django 5.2.3 on 2025-06-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_loanabovesavingsapplication_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanabovesavingsapplication',
            name='has_full_kyc',
        ),
        migrations.RemoveField(
            model_name='loanabovesavingsapplication',
            name='has_signed_deduction_agreement',
        ),
        migrations.RemoveField(
            model_name='loanabovesavingsapplication',
            name='has_valid_surety_bond',
        ),
        migrations.RemoveField(
            model_name='loanabovesavingsapplication',
            name='loan_purpose_clearly_defined',
        ),
        migrations.RemoveField(
            model_name='loanwithinsavingsapplication',
            name='has_full_kyc',
        ),
        migrations.RemoveField(
            model_name='loanwithinsavingsapplication',
            name='loan_purpose_clearly_defined',
        ),
        migrations.RemoveField(
            model_name='mortgageloanapplication',
            name='has_full_kyc',
        ),
        migrations.RemoveField(
            model_name='mortgageloanapplication',
            name='has_land_title_in_borrower_name',
        ),
        migrations.RemoveField(
            model_name='mortgageloanapplication',
            name='has_legal_mortgage_agreement',
        ),
        migrations.RemoveField(
            model_name='mortgageloanapplication',
            name='has_power_of_attorney',
        ),
        migrations.RemoveField(
            model_name='mortgageloanapplication',
            name='has_supporting_documents',
        ),
        migrations.RemoveField(
            model_name='mortgageloanapplication',
            name='loan_purpose_valid',
        ),
        migrations.RemoveField(
            model_name='salarybackedloanapplication',
            name='has_copy_of_effective_service',
        ),
        migrations.RemoveField(
            model_name='salarybackedloanapplication',
            name='has_full_kyc',
        ),
        migrations.RemoveField(
            model_name='salarybackedloanapplication',
            name='has_irrevocable_salary_transfer_doc',
        ),
        migrations.RemoveField(
            model_name='salarybackedloanapplication',
            name='loan_purpose_clearly_defined',
        ),
        migrations.RemoveField(
            model_name='standingorderloanapplication',
            name='has_full_kyc',
        ),
        migrations.RemoveField(
            model_name='standingorderloanapplication',
            name='loan_purpose_clearly_defined',
        ),
        migrations.AddField(
            model_name='loanabovesavingsapplication',
            name='signed_deduction_agreement_document',
            field=models.FileField(blank=True, null=True, upload_to='above_savings_docs/deduction_agreements/'),
        ),
        migrations.AddField(
            model_name='loanabovesavingsapplication',
            name='valid_surety_bond_document',
            field=models.FileField(blank=True, null=True, upload_to='above_savings_docs/surety_bonds/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='full_kyc_document',
            field=models.FileField(blank=True, null=True, upload_to='kyc_docs/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='loan_purpose_document',
            field=models.FileField(blank=True, null=True, upload_to='loan_purpose_docs/'),
        ),
        migrations.AddField(
            model_name='mortgageloanapplication',
            name='land_title_document',
            field=models.FileField(blank=True, null=True, upload_to='mortgage_docs/land_titles/'),
        ),
        migrations.AddField(
            model_name='mortgageloanapplication',
            name='legal_mortgage_agreement_document',
            field=models.FileField(blank=True, null=True, upload_to='mortgage_docs/legal_agreements/'),
        ),
        migrations.AddField(
            model_name='mortgageloanapplication',
            name='power_of_attorney_document',
            field=models.FileField(blank=True, null=True, upload_to='mortgage_docs/poa/'),
        ),
        migrations.AddField(
            model_name='mortgageloanapplication',
            name='supporting_documents',
            field=models.FileField(blank=True, null=True, upload_to='mortgage_docs/supporting/'),
        ),
        migrations.AddField(
            model_name='salarybackedloanapplication',
            name='copy_of_effective_service_document',
            field=models.FileField(blank=True, null=True, upload_to='salary_docs/effective_service/'),
        ),
        migrations.AddField(
            model_name='salarybackedloanapplication',
            name='irrevocable_salary_transfer_document',
            field=models.FileField(blank=True, null=True, upload_to='salary_docs/transfer_docs/'),
        ),
    ]
