# Generated by Django 5.2.7 on 2025-11-01 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_alter_agriculturalloanapplication_loan_purpose_category'),
        ('credit_unions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='credit_union',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency', to='credit_unions.creditunion'),
        ),
        migrations.AlterField(
            model_name='agriculturalloanapplication',
            name='total_cost_estimate_document',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='businessloanapplication',
            name='land_documents_attached',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='containerloanapplication',
            name='bill_of_lading_document',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='containerloanapplication',
            name='custom_clearance_plan_document',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dailysavingsloanapplication',
            name='signed_deduction_agreement_document',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dailysavingsloanapplication',
            name='valid_surety_bond_document',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mortgageloanapplication',
            name='legal_mortgage_agreement_document',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='realestateloanapplication',
            name='legal_mortgage_agreement_document_re',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='salarybackedloanapplication',
            name='copy_of_effective_service_document',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='salarybackedloanapplication',
            name='irrevocable_salary_transfer_document',
            field=models.BooleanField(default=False),
        ),
    ]
