# Generated by Django 5.2.3 on 2025-07-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_remove_loanabovesavingsapplication_has_full_kyc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='full_kyc_document',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='current_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='duration_with_mfi_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='identity_card_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='marital_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='num_loans_other_mfi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
