# Generated by Django 5.2.7 on 2025-11-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_loanapplication_credit_union_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarybackedloanapplication',
            name='salary_passing_union_ge_3_months',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
