# Generated by Django 5.2.3 on 2025-07-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_remove_loanapplication_full_kyc_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='account_number',
            field=models.CharField(blank=True, help_text="Applicant's MFI Account Number", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='savings_balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Applicant's current savings balance at the MFI", max_digits=15, null=True),
        ),
    ]
